### ISSUE TITLE
Changes in Contribution.md

### ISSUE THREAD

**Issue by pawar-jaydeep** [nikhil25803/fundRaiser#1]
hey, you can make the Contribution.md file much easier to read and use.
just by making a few changes like using the single command for the new branch and checkout.

**Comment by pawar-jaydeep** [comment]
I would like to work on it.
can you pls assign this issue to me?

**Comment by nikhil25803** [comment]
Hey @pawar-jaydeep | Sorry for replying late.
Go ahead and make the changes :)
